# -*- coding: utf-8 -*-

# Copyright (C) 2016 Ross Scroggs All Rights Reserved.
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""GAM messages

"""

# These values can be translated into other languages
ACCESS_FORBIDDEN = 'Access Forbidden'
ACTION_APPLIED = 'Action Applied'
ADMIN_STATUS_CHANGED_TO = 'Admin Status Changed to'
ALL = 'All'
ALREADY_EXISTS_USE_MERGE_ARGUMENT = 'Already exists; use the "merge" argument to merge the labels'
API_ACCESS_DENIED = 'API access Denied.\nPlease make sure the Client ID: {0} is authorized for the appropriate scopes {1}'
API_ERROR_SETTINGS = 'API error, some settings not set'
AS = 'as'
BAD_REQUEST = 'Bad Request'
BATCH = 'Batch'
BATCH_CSV_LOOP_DASH_DEBUG_INCOMPATIBLE = '"gam {0} - ..." is not compatible with debugging. Disable debugging by setting debug_level = 0 in gam.cfg'
BATCH_NOT_PROCESSED_ERRORS = '{0}batch file: {1}, not processed, {2} {3}\n'
CAN_NOT_BE_DOWNLOADED = 'Can not be downloaded'
COMMIT_BATCH_COMPLETE = 'commit-batch - running processes finished, proceeding\n'
COMMIT_BATCH_WAIT_N_PROCESSES = 'commit-batch - waiting for {0} running {1} to finish before proceeding\n'
CONTAINS_AT_LEAST_1_ITEM = 'Contains at least 1 item'
COUNT_N_EXCEEDS_MAX_TO_PROCESS_M = 'Count {0} exceeds maximum to {1} {2}'
CSV_DATA_ALREADY_SAVED = 'CSV data already saved'
DATA_FIELD_MISMATCH = 'datafield {0} does not match saved datafield {1}'
DATA_UPLOADED_TO_DRIVE_FILE = 'Data uploaded to Drive File'
DIRECTLY_IN_THE = ' directly in the {0}'
DOES_NOT_EXIST = 'Does not exist'
DOES_NOT_EXIST_OR_HAS_INVALID_FORMAT = '{0}: {1}, Does not exist or has invalid format'
DOMAIN_NOT_VERIFIED_SECONDARY = 'Domain is not a verified secondary domain'
DO_NOT_EXIST = 'Do not exist'
DUPLICATE = 'Duplicate'
EITHER = 'Either'
ENTITY_DOES_NOT_EXIST = '{0} does not exist'
ERROR = 'error'
EXECUTE_GAM_OAUTH_CREATE = '\nPlease execute "gam oauth create"\n'
EXISTS = 'Exists'
EXPECTED = 'Expected'
FAILED_TO_PARSE_AS_JSON = 'Failed to parse as JSON'
FIELD_NOT_FOUND_IN_SCHEMA = 'Field {0} not found in schema {1}'
FINISHED = 'Finished'
FOR = 'for'
FORBIDDEN = 'Forbidden'
FORMAT_NOT_AVAILABLE = 'Format ({0}) not available'
FORMAT_NOT_DOWNLOADABLE = 'Format not downloadable'
FROM = 'From'
GAM_EXITING_FOR_UPDATE = 'GAM is now exiting so that you can overwrite this old version with the latest release'
GAM_OUT_OF_MEMORY = 'GAM has run out of memory. If this is a large G Suite instance, you should use a 64-bit version of GAM on Windows or a 64-bit version of Python on other systems.'
GETTING = 'Getting'
GETTING_ALL = 'Getting all'
GOOGLE_EARLIEST_REPORT_TIME = 'Google earliest report time'
GOT = 'Got'
GUARDIAN_INVITATION_STATUS_NOT_PENDING = 'Guardian invitation status is not PENDING'
HAS_CHILD_ORGS = 'Has child {0}'
HEADER_NOT_FOUND_IN_CSV_HEADERS = 'Header "{0}" not found in CSV headers of "{1}".'
HELP_SYNTAX = 'Help: Syntax in file {0}\n'
HELP_WIKI = 'Help: Documentation is at {0}\n'
HIT_CONTROL_C_TO_UPDATE = '\n\nHit CTRL+C to visit the GAM website and download the latest release or wait 15 seconds continue with this boring old version. GAM won\'t bother you with this announcement for 1 week or you can turn off update checks by setting no_update_check = true in gam.cfg'
INSTRUCTIONS_CHECK_AUTHORIZATIONS = 'Please run\n\ngam oauth info\ngam user <user> check serviceaccount\n\nto verify authorizations.\n'
INSTRUCTIONS_CLIENT_SECRETS_JSON = 'Please run\n\ngam create project\ngam oauth create\n\nto create and authorize a Client account.\n'
INSTRUCTIONS_OAUTH2SERVICE_JSON = 'Please run\n\ngam create project\ngam user <user> check serviceaccount\n\nto create and authorizee a Service account.\n'
INSUFFICIENT_PERMISSIONS_TO_PERFORM_TASK = 'Insufficient permissions to perform this task'
INVALID = 'Invalid'
INVALID_ALIAS = 'Invalid Alias'
INVALID_ENTITY_MESSAGE = 'Invalid {0}, {1}'
INVALID_GROUP = 'Invalid Group'
INVALID_JSON_INFORMATION = 'Google API reported Invalid JSON Information'
INVALID_MESSAGE_ID = 'Invalid message id(s)'
INVALID_ORGUNIT = 'Invalid Organizational Unit'
INVALID_OWNER_TYPE = 'role {0} not allowed with {1}'
INVALID_PATH = 'Invalid Path'
INVALID_QUERY = 'Invalid Query'
INVALID_REQUEST = 'Invalid Request'
INVALID_ROLE = 'Invalid Role'
INVALID_SCHEMA_VALUE = 'Invalid Schema Value'
INVALID_SCOPE = 'Invalid Scope'
INVALID_SITE = 'Invalid Site ({0}), must match pattern ({1})'
INVALID_TIME_RANGE = '{0} {1} must be greater than/equal to {2} {3}'
IS_REQD_TO_CHG_PWD_NO_DELEGATION = 'is required to change password at next login. You must change password or clear changepassword flag for delegation.'
IS_SUSPENDED_NO_DELEGATION = 'is suspended. You must unsuspend for delegation.'
LOOKING_UP_GOOGLE_UNIQUE_ID = 'Looking up Google Unique ID'
MARKED_AS = 'Marked as'
MATCHED_THE_FOLLOWING = 'Matched the following'
MAXIMUM_OF = 'maximum of'
MAY_TAKE_SOME_TIME_ON_A_LARGE = 'may take some time on a large'
MISMATCH_SEARCH_REPLACE_SUBFIELDS = 'The number of subfields ({0}) in search "{1}" does not match the number of subfields ({2}) in replace "{3}"'
NESTED_LOOP_CMD_NOT_ALLOWED = 'Command can not be nested.'
NEW_OWNER_MUST_DIFFER_FROM_OLD_OWNER = 'New owner must differ from old owner'
NON_BLANK = 'Non-blank'
NON_EMPTY = 'Non-empty'
NOT_A = 'Not a'
NOT_ALLOWED = 'Not Allowed'
NOT_AN_ENTITY = 'Not a {0}'
NOT_A_GUARDIAN_OR_INVITATION = 'Not a Guardian or Guardian Invitation'
NOT_FOUND = 'Not Found'
NOT_OWNED_BY = 'Not owned by {0}'
NOT_WRITABLE = 'Not Writable'
NOW_THE_PRIMARY_DOMAIN = 'Now the primary domain'
NO_CSV_FILE_DATA_SAVED = 'No CSV file data saved'
NO_CSV_FILE_SUBKEYS_SAVED = 'No CSV file subkeys saved'
NO_ENTITIES_FOUND = 'No {0} found'
NO_ENTITIES_MATCHED = 'No {0} matched'
NO_FILTER_ACTIONS = 'No {0} actions specified'
NO_FILTER_CRITERIA = 'No {0} criteria specified'
NO_LABELS_MATCH = 'No Labels match'
NO_MESSAGES_WITH_LABEL = 'No Messages with Label'
NO_PRINT_JOBS = 'No Print Jobs'
NO_PYTHON_SSL = 'You don\'t have the Python SSL module installed so we can\'t verify SSL Certificates. You can fix this by installing the Python SSL module or you can live on the edge and turn SSL validation off by setting no_verify_ssl = true in gam.cfg'
NO_SCOPES_FOR_API = 'There are no scopes authorized for the {0}'
NO_TRANSFER_LACK_OF_DISK_SPACE = 'Cowardly refusing to perform migration due to lack of target drive space.'
ONLY_ONE_OWNER_ALLOWED = 'Only one owner allowed'
OR = 'or'
PLEASE_SELECT_ENTITY_TO_PROCESS = '{0} {1} found, please select the correct one to {2} and specify with {3}'
PROCESSING_ITEM_N = 'Processing item {0}\n'
REFUSING_TO_DEPROVISION_DEVICES = 'Refusing to deprovision {0} devices because acknowledge_device_touch_requirement not specified.\nDeprovisioning a device means the device will have to be physically wiped and re-enrolled to be managed by your domain again.\nThis requires physical access to the device and is very time consuming to perform for each device.\nPlease add "acknowledge_device_touch_requirement" to the GAM command if you understand this and wish to proceed with the deprovision.\nPlease also be aware that deprovisioning can have an effect on your device license count.\nSee https://support.google.com/chrome/a/answer/3523633 for full details.'
REQUEST_COMPLETED_NO_FILES = 'Request completed but no results/files were returned, try requesting again'
REQUEST_NOT_COMPLETE = 'Request needs to be completed before downloading, current status is: {0}'
RESULTS_TOO_LARGE_FOR_GOOGLE_SPREADSHEET = 'Results are too large for Google Spreadsheets. Uploading as a regular CSV file.'
SCHEMA_WOULD_HAVE_NO_FIELDS = '{0} would have no {1}'
SCOPE_AUTHORIZATION_FAILED = 'Some scopes failed! Please go to:\n\nhttps://admin.google.com/{0}/AdminHome?#OGX:ManageOauthClients\n\nand grant Service Account Client name:\n\n{1}\n\nAccess to scopes:\n\n{2}'
SCOPE_AUTHORIZATION_PASSED = 'All scopes passed!\nService Account Client name {0} is fully authorized.'
SELECTED = 'Selected'
SERVICE_NOT_APPLICABLE_THIS_ADDRESS = 'Service not applicable for this address: {0}'
SERVICE_NOT_APPLICABLE = 'Service not applicable/Does not exist'
SKU_PRODUCT_MISMATCH = 'Product {0} of old SKU does not match product {1} of new SKU'
STARTING_THREAD = 'Starting thread'
STRING_LENGTH = 'string length'
SUBKEY_FIELD_MISMATCH = 'subkeyfield {0} does not match saved subkeyfield {1}'
SUBSCRIPTION_NOT_FOUND = 'Could not find subscription'
THAT_MATCHED_QUERY = 'that matched query'
THAT_MATCH_QUERY = 'that match query'
TO = 'To'
UNAVAILABLE = 'Unavailable'
UNKNOWN = 'Unknown'
UNKNOWN_API_OR_VERSION = 'Unknown Google API or version: ({0}), contact {1}'
UNKNOWN_COMMAND_SELECTOR = 'Unknown command or selector'
USER_IN_OTHER_DOMAIN = '{0}: {1} in other domain.'
USE_DOIT_ARGUMENT_TO_PERFORM_ACTION = 'Use the "doit" argument to perform action'
USE_RECURSIVE_ARGUMENT_TO_COPY_FOLDERS = 'Use "recursive" argument to copy folders'
USING_N_PROCESSES = 'Using {0} processes...\n'
WAITING_FOR_PROCESSES_TO_COMPLETE = 'Waiting for running processes to finish before proceeding...'
WITH = 'with'
WOULD_MAKE_MEMBERSHIP_CYCLE = 'Would make membership cycle'
